#!/usr/bin/env python3
import sys
import random
from bsddb3 import db

DATABASE = "/tmp/doupton_db/main.db"
INDEXFILE = "/tmp/doupton_db/indexfile.db"
DB_SIZE = 100000
SEED = 1000000

#Code taken from sample code in notes
def populate( datebase ):
    for index in range( DB_SIZE ):
        krng = 64 + random.randint( 0, 63 )
        key = ""
        for i in range(krng):
            key += str( chr( 97 + random.randint( 0, 25 ) ) )
        vrng = 64 + random.randint( 0, 63 )
        value = ""
        for i in range(vrng):
            value += str( chr( 97 + random.randint( 0, 25 ) ) )

        key = key.encode( encoding="UTF-8" )
        value = value.encode( encoding="UTF-8" )
        database.put( key, value )

    cur = database.cursor()
    iter =  cur.first()
    while iter:
        print(iter[0].decode("UTF-8"))
        print(iter[1].decode("UTF-8"))
        print()
        iter = cur.next()

    database.close() 
    

#=============================================================================
# Function:
#=============================================================================
# args:
#
# wat do:
#
def create_DB( datatype ):
        ##Remember to mkdir /tmp/doupton_db
    print("Creating Database...") 
    try: 
        database = db.DB()
        database.open( DATABASE, None , datatype[0], db.DB_CREATE )
        if datatype[1]:
            second_database = db.DB()
            second_database.open( INDEXFILE, None, datatype[1], db.DB_CREATE )
    except:
        print("Something went wrong")
        return
    populate( datebase )

    return database
    
#=============================================================================
# Function:
#=============================================================================
# args:
#
# wat do:
#
def get_withKey( datatype ):
    print("Get with key")
    pass
 
#=============================================================================
# Function:
#=============================================================================
# args:
#
# wat do:
#
def get_withData( datatype ):
    print("Get with data")
    pass

#=============================================================================
# Function:
#=============================================================================
# args:
#
# wat do:
#
def get_withRange( datatype ):
    print("Get with range")
    pass

#=============================================================================
# Function:
#=============================================================================
# args:
#
# wat do:
#
def demolish_DB( datatype ):
    print("Demolish DB")
    pass

#=============================================================================
# Function:
#=============================================================================
# args:
#
# wat do:
#
# Returns a tuple of (primary datatype, secondary datatype)
def get_datatype():
    if len( sys.argv ) == 1:
        errMsg = sys.argv[0] + ": No DB type specified\n" +\
                 "Try '" + sys.argv[0] + " help' for more information.\n"
        print( errMsg )
        exit()
    if len( sys.argv ) > 2:
        errMsg = sys.argv[0] + ": too many options specified\n" +\
                 "Try '" + sys.argv[0] + " help' for more information.\n"
        print( errMsg )
        exit()
    datatype = sys.argv[1].lower()
    if datatype == "btree":
        datatype = (db.DB_BTREE, None)
    elif datatype == "hash":
        datatype = (db.DB_HASH, None)
    elif datatype == 'indexfile':
        datatype == (db.DB_BTREE, db.DB_HASH)
    elif datatype == "help":
        helpMsg = "Usage: 'mydbtest OPTION'\n" +\
                  "options: 'btree', 'hash', 'indexfile', 'help'\n"
        print( helpMsg )
        exit()
    else:
        errMsg = sys.argv[0] + ": invalid option -- '" +\
                 sys.argv[1] + "'\n" +\
                 "Try '" + sys.argv[0] + " help' for more information.\n"
        print( errMsg )
        exit()
    return datatype
    
#=============================================================================
# Function:
#=============================================================================
# args:
#
# wat do:
#
def showoptions( options ):
    #print(chr(27) + "[2J")
    print( "=" * 80 )
    print( " =" * 40 )
    print( "dbDB".center(80) )
    print( "= " * 40 )
    print()
    for index in range( len( options ) ):
        try:
            optStr = "[" + str(index) + "]: " + str( options[index].__name__ )
            print( optStr )
        except:
            optStr = "[" + str(index) + "]: Exit "
            print( optStr )

#=============================================================================
# Function:
#=============================================================================
# args:
#
# wat do:
#
def main():
    options = [ create_DB, get_withKey, get_withData, \
                get_withRange, demolish_DB, quit ]
    datatype = get_datatype()
    while True:
        showoptions( options )
        option = input("dbDB>")
        # Ensure that the choice is an integer
        try:
            option = int( option )
        except:
            print( "Error:\t Choice must be an integer." )
            continue
        # Ensure that the choice is a valid choice
        if option not in range( len(options) ):
            print( "Error:\t You must choose one of the listed options." )
            continue

main()

